// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchtus7EoquaMMbnoITHlkxkune8XuSVo',
    appId: '1:523086236367:web:539888e9ade50e578d05ba',
    messagingSenderId: '523086236367',
    projectId: 'resque-hyeah2026',
    authDomain: 'resque-hyeah2026.firebaseapp.com',
    storageBucket: 'resque-hyeah2026.firebasestorage.app',
    measurementId: 'G-L5DFSXPEYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_w0N-HdWv9DADKQOWPvBFgkPUIlx0WN4',
    appId: '1:523086236367:android:76148c21d32e30778d05ba',
    messagingSenderId: '523086236367',
    projectId: 'resque-hyeah2026',
    databaseURL: 'https://resque-hyeah2026-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'resque-hyeah2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8Ts_kQghkAS3GUstv-VGBSO3CQNKcfk',
    appId: '1:523086236367:ios:748e49883c4fcda08d05ba',
    messagingSenderId: '523086236367',
    projectId: 'resque-hyeah2026',
    storageBucket: 'resque-hyeah2026.firebasestorage.app',
    iosBundleId: 'com.example.resque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR8Ts_kQghkAS3GUstv-VGBSO3CQNKcfk',
    appId: '1:523086236367:ios:748e49883c4fcda08d05ba',
    messagingSenderId: '523086236367',
    projectId: 'resque-hyeah2026',
    storageBucket: 'resque-hyeah2026.firebasestorage.app',
    iosBundleId: 'com.example.resque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchtus7EoquaMMbnoITHlkxkune8XuSVo',
    appId: '1:523086236367:web:f47250f95594d75e8d05ba',
    messagingSenderId: '523086236367',
    projectId: 'resque-hyeah2026',
    authDomain: 'resque-hyeah2026.firebaseapp.com',
    storageBucket: 'resque-hyeah2026.firebasestorage.app',
    measurementId: 'G-CY7157R1KG',
  );
}
